baseURL = "https://goldrevboy.github.io/my-portfolio/"
title = "Parth Dabas"
languageCode = "en-us"
theme = "coder"

pagination.pagerSize = 10

enableEmoji = true
[params]
  author = "Parth Dabas"
  info = "Student | Developer | Researcher"
  description = "Portfolio and blog of Parth Dabas"
  keywords = "portfolio,developer,blog"
  avatarURL = "images/avatar.jpg"

  colorScheme = "auto"
  hideColorSchemeToggle = false

  customCSS = []
  customJS = []

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 3

